### ISSUE TITLE
wrong closing bracket

### ISSUE THREAD

**Issue by RoadJDK** [Akjo03/WinClean#31]
<data name="ArgParse.PartNotFound" xml:space="preserve">
    <value>Part {part_name} was not found!</value>
    <comment>Part "{part_name]" was not found!</comment>
  </data>

"{part_name]"

**Comment by Akjo03** [comment]
How can I reproduce this? I might know where this error is but I cannot imagine how [partInput in the ArgumentParser](https://github.com/Akjo03/WinClean/blob/42af9556bb6c468c1642c122e964f36915fa2116/ArgumentParser.cs#L41) would not be set... The error comes from [here](https://github.com/Akjo03/WinClean/blob/42af9556bb6c468c1642c122e964f36915fa2116/ArgumentParser.cs#L56). 

Normally this should replace "{part_name}" in the localized string with the part name specified (which is not really a name but just the number xD). Did you specify any parts? Because without any parts specified (through cmd) it will just do no parts... 

In PowerShell, you will have to insert parts because the syntax of the arguments is "PowerShell-conform" and with that, you will have to specify parts... If you leave the ":" out on the parts argument it should just say that it errored out on parsing the arguments. 

So this should never happen!

PS: This comment is just way too long xD
